project:
  sub-project: "/spring-boot-project/spring-boot/"
repo:
  url: "https://github.com/spring-projects/spring-boot"
  commit: "3ed1f1a064a10e53adc2ad8c0b46a4b2c148ee21"
  target-dir: "/home/jerome/Documents/Assistant/Recherche/joular-scripts/test-sentinel-copy/spring-boot-clone"
log:
  level: INFO