project:
  sub-project: "/spring-boot-project/spring-boot"
  show-project-logs: true
  package-prefix: "org.springframework"
repo:
  url: "https://github.com/spring-projects/spring-boot"
  commit: "3ed1f1a064a10e53adc2ad8c0b46a4b2c148ee21"
  target-dir: "/home/jerome/Documents/Assistant/Recherche/joular-scripts/test-sentinel-copy/spring-boot-clone"
  overwrite: true
log:
  level: INFO
code-constructors-instrumentation-path: "/home/jerome/Documents/Assistant/Recherche/joular-scripts/sentinel-experiments/src/main/java/be/unamur/snail/spoon/constructor_instrumentation"
time-out: 120
execution-plan:
  test-command: "./gradlew clean spring-boot-project:spring-boot:test --rerun-tasks --tests org.springframework.boot.ApplicationEnvironmentTests.propertyResolverIsOptimizedForConfigurationProperties"
  ignore-failures: false
  ignore-spoon-failures: true
database:
  mode: dev
  # dev-specific
  plugins-directory: "/home/jerome/Documents/Assistant/Recherche/joular-scripts/sentinel-backend/plugins"
  backend-path: "/home/jerome/Documents/Assistant/Recherche/joular-scripts/sentinel-backend/"
  # prod-specific
  ssh-user: "jmaquoi"
  ssh-host: "ava.info.unamur.be"